"use client";

import { useEffect, useRef, useState } from "react";
import { ConversationProvider, useConversation } from "@elevenlabs/react";
import { motion } from "framer-motion";
import { VOICE_OPTIONS } from "@/lib/ai/voices";
import { topicById } from "@/lib/ai/topics";
import type { VoiceReport } from "@/lib/ai/prompts/voice-review";
import { attachKonusmaScore } from "@/lib/diagnostic/result";
import { VoicePackModal } from "@/components/VoicePackModal";
import { useI18n, type Locale } from "@/lib/i18n";
import { pick } from "@/lib/localized";
import { awardXp, XP } from "@/lib/xp";

type Mode = "free" | "bolum1" | "bolum2" | "bolum3" | "full";
type Line = { source: "user" | "ai"; text: string };
type Phase = "idle" | "starting" | "live" | "wrapping" | "ended";

const MODES: Mode[] = ["bolum1", "bolum2", "bolum3", "full", "free"];

// oral wrap-up instruction sent as a user message (a message, unlike a
// contextual update, always triggers a reply turn) when the student ends the
// lesson. Billing is cut server-side at the press — the wrap-up is free.
// TURKISH ONLY by design: the voice model's Russian/Kazakh came out broken
// (founder-reported), so the interface-language evaluation lives entirely in
// the WRITTEN review generated by the text model (buildVoiceReviewSystem).
const WRAP_NOTE =
  "SİSTEM NOTU: Öğrenci dersi şimdi bitiriyor. SADECE TÜRKÇE, basit ve net bir KAPANIŞ yap (en fazla 25-30 saniye): 1) tek cümleyle dersin özeti, 2) bir güçlü yön ve en önemli bir hata — çok kısa, 3) 'Ayrıntılı yazılı değerlendirmen birazdan ekranda görünecek' de, 4) sıcak bir veda. Türkçe DIŞINDA hiçbir dilde KONUŞMA, değerlendirmeyi başka dilde yapmaya ÇALIŞMA.";

const T = {
  ru: {
    title: "Живой урок с AI-преподавателем",
    subtitle: "Урок с учебным фокусом: преподаватель ведёт диалог по темам твоего уровня, исправляет по ходу и в конце разбирает по критериям TÖMER Konuşma.",
    modes: { bolum1: "Bölüm 1 · Диалог", bolum2: "Bölüm 2 · Монолог", bolum3: "Bölüm 3 · Мнение", full: "Полный экзамен", free: "Свободная беседа" },
    voice: "Голос преподавателя", start: "Начать урок", starting: "Подключение…",
    end: "Завершить с итогом", endNow: "закончить без итога",
    endHint: "Закончил говорить или не знаешь, что сказать дальше? Жми «Завершить с итогом» — получишь разбор с оценками и рекомендациями.", wrapping: "Преподаватель подводит итог — дослушай…", wrapFreeNote: "Минуты уже не списываются — итог бесплатный.",
    listening: "Слушает тебя — говори", speaking: "Преподаватель говорит…", minutes: "Минуты сегодня", purchased: "докупленные",
    focus: "Фокус урока", transcript: "Транскрипт", ended: "Урок завершён", spent: "Потрачено", min: "мин",
    fromBase: "из дневных", fromCredits: "из докупленных", short: "Сессия была короче 10 секунд — минуты не списаны.",
    reportPreparing: "Готовим письменный разбор…", reportTitle: "Разбор урока · TÖMER Konuşma",
    settleFailed: "Запись урока ещё обрабатывается — разбор не получен.", settleRetry: "Получить разбор",
    crit: { fluency: "Беглость", grammar: "Грамматика", vocab: "Лексика", coherence: "Связность" },
    errors: "Ошибки из разговора", noErrors: "Заметных ошибок в разговоре не найдено!", rule: "Правило",
    topicsWorked: "Проработанные темы", nextSteps: "Что дальше", reportNone: "Разговор был слишком коротким для разбора.",
    again: "Ещё урок",
    errAuth: "Войди в аккаунт, чтобы начать урок.", errMic: "Нужен доступ к микрофону — разреши его в браузере и попробуй снова.",
    errNoMinutes: "На сегодня минуты закончились. База обновится в полночь — или докупи пакет минут.", buyMinutes: "Докупить минуты",
    errUnavailable: "Голосовой урок временно недоступен. Попробуй позже.", errGeneric: "Не получилось подключиться. Попробуй ещё раз.",
    errBusy: (n: number) => `Преподаватель сейчас занят — все места на уроке. Освободится в течение ~${n} мин, мы проверяем автоматически.`, busyFree: "Преподаватель освободился — можно начинать!",
    hint: "Говори свободно — ошибки это нормально, преподаватель поправит.",
  },
  en: {
    title: "Live lesson with the AI teacher",
    subtitle: "A lesson with a teaching focus: the teacher steers the dialogue around your level's topics, corrects on the fly and reviews you against TÖMER Konuşma criteria.",
    modes: { bolum1: "Bölüm 1 · Dialogue", bolum2: "Bölüm 2 · Monologue", bolum3: "Bölüm 3 · Opinion", full: "Full exam", free: "Free talk" },
    voice: "Teacher's voice", start: "Start lesson", starting: "Connecting…",
    end: "Finish with feedback", endNow: "end without feedback",
    endHint: "Done talking, or not sure what to say next? Hit \"Finish with feedback\" — you'll get a review with scores and recommendations.", wrapping: "The teacher is wrapping up — listen…", wrapFreeNote: "The clock has stopped — the wrap-up is free.",
    listening: "Listening — go ahead", speaking: "Teacher is speaking…", minutes: "Minutes today", purchased: "purchased",
    focus: "Lesson focus", transcript: "Transcript", ended: "Lesson finished", spent: "Spent", min: "min",
    fromBase: "from daily", fromCredits: "from purchased", short: "The session was under 10 seconds — no minutes were charged.",
    reportPreparing: "Preparing the written review…", reportTitle: "Lesson review · TÖMER Konuşma",
    settleFailed: "The lesson recording is still processing — no review yet.", settleRetry: "Get the review",
    crit: { fluency: "Fluency", grammar: "Grammar", vocab: "Vocabulary", coherence: "Coherence" },
    errors: "Errors from the conversation", noErrors: "No notable errors found in the conversation!", rule: "Rule",
    topicsWorked: "Topics worked on", nextSteps: "Next steps", reportNone: "The conversation was too short for a review.",
    again: "Another lesson",
    errAuth: "Sign in to start a lesson.", errMic: "Microphone access is required — allow it in your browser and retry.",
    errNoMinutes: "You're out of minutes for today. The base quota resets at midnight — or top up with a minute pack.", buyMinutes: "Buy minutes",
    errUnavailable: "The voice lesson is temporarily unavailable. Please try later.", errGeneric: "Couldn't connect. Please try again.",
    errBusy: (n: number) => `The teacher is busy right now — all lesson slots are taken. A slot frees up within ~${n} min; we re-check automatically.`, busyFree: "The teacher is free — you can start!",
    hint: "Speak freely — mistakes are fine, the teacher will correct you.",
  },
  tr: {
    title: "AI öğretmenle canlı ders",
    subtitle: "Öğrenme odaklı ders: öğretmen diyaloğu seviyene uygun konular etrafında yürütür, anında düzeltir ve sonunda TÖMER Konuşma ölçütlerine göre değerlendirir.",
    modes: { bolum1: "Bölüm 1 · Karşılıklı", bolum2: "Bölüm 2 · Sözlü anlatım", bolum3: "Bölüm 3 · Görüş", full: "Tam sınav", free: "Serbest sohbet" },
    voice: "Öğretmenin sesi", start: "Derse başla", starting: "Bağlanıyor…",
    end: "Değerlendirmeyle bitir", endNow: "değerlendirmesiz bitir",
    endHint: "Söyleyeceklerin bitti mi, ne diyeceğinden emin değil misin? \"Değerlendirmeyle bitir\"e bas — puanlı ve önerili bir değerlendirme alırsın.", wrapping: "Öğretmen dersi topluyor — dinle…", wrapFreeNote: "Dakika sayacı durdu — kapanış ücretsiz.",
    listening: "Dinliyor — konuş", speaking: "Öğretmen konuşuyor…", minutes: "Bugünkü dakikalar", purchased: "satın alınan",
    focus: "Dersin odağı", transcript: "Döküm", ended: "Ders bitti", spent: "Harcanan", min: "dk",
    fromBase: "günlükten", fromCredits: "satın alınandan", short: "Oturum 10 saniyeden kısaydı — dakika düşülmedi.",
    reportPreparing: "Yazılı değerlendirme hazırlanıyor…", reportTitle: "Ders değerlendirmesi · TÖMER Konuşma",
    settleFailed: "Ders kaydı hâlâ işleniyor — değerlendirme alınamadı.", settleRetry: "Değerlendirmeyi al",
    crit: { fluency: "Akıcılık", grammar: "Dil bilgisi", vocab: "Kelime", coherence: "Tutarlılık" },
    errors: "Konuşmadaki hatalar", noErrors: "Konuşmada kayda değer hata bulunamadı!", rule: "Kural",
    topicsWorked: "Çalışılan konular", nextSteps: "Sonraki adımlar", reportNone: "Konuşma değerlendirme için çok kısaydı.",
    again: "Yeni ders",
    errAuth: "Derse başlamak için giriş yap.", errMic: "Mikrofon izni gerekli — tarayıcıda izin ver ve tekrar dene.",
    errNoMinutes: "Bugünkü dakikaların bitti. Taban kota gece yarısı yenilenir — ya da dakika paketi al.", buyMinutes: "Dakika al",
    errUnavailable: "Sesli ders geçici olarak kullanılamıyor. Daha sonra dene.", errGeneric: "Bağlanılamadı. Tekrar dene.",
    errBusy: (n: number) => `Öğretmen şu an meşgul — tüm ders yerleri dolu. ~${n} dk içinde boşalır; otomatik kontrol ediyoruz.`, busyFree: "Öğretmen boşaldı — başlayabilirsin!",
    hint: "Rahat konuş — hata yapmak normal, öğretmen düzeltir.",
  },
  kk: {
    title: "AI ұстазбен жанды сабақ",
    subtitle: "Оқу фокусы бар сабақ: ұстаз диалогты деңгейіңе сай тақырыптармен жүргізеді, қатеңді сол сәтте түзетеді, соңында TÖMER Konuşma өлшемдерімен талдайды.",
    modes: { bolum1: "Bölüm 1 · Диалог", bolum2: "Bölüm 2 · Монолог", bolum3: "Bölüm 3 · Пікір", full: "Толық емтихан", free: "Еркін әңгіме" },
    voice: "Ұстаздың дауысы", start: "Сабақты бастау", starting: "Қосылуда…",
    end: "Қорытындымен аяқтау", endNow: "қорытындысыз аяқтау",
    endHint: "Айтарың бітті ме, не дерің белгісіз бе? «Қорытындымен аяқтау» бас — баға мен ұсыныстары бар талдау аласың.", wrapping: "Ұстаз қорытынды айтып жатыр — тыңда…", wrapFreeNote: "Минуттар енді есептелмейді — қорытынды тегін.",
    listening: "Тыңдап тұр — сөйлей бер", speaking: "Ұстаз сөйлеп жатыр…", minutes: "Бүгінгі минуттар", purchased: "сатып алынған",
    focus: "Сабақ фокусы", transcript: "Транскрипт", ended: "Сабақ аяқталды", spent: "Жұмсалды", min: "мин",
    fromBase: "күнделіктіден", fromCredits: "сатып алынғаннан", short: "Сессия 10 секундтан қысқа болды — минут есептелген жоқ.",
    reportPreparing: "Жазбаша талдау дайындалуда…", reportTitle: "Сабақ талдауы · TÖMER Konuşma",
    settleFailed: "Сабақ жазбасы әлі өңделуде — талдау алынбады.", settleRetry: "Талдауды алу",
    crit: { fluency: "Еркіндік", grammar: "Грамматика", vocab: "Лексика", coherence: "Байланыстылық" },
    errors: "Әңгімедегі қателер", noErrors: "Әңгімеде елеулі қате табылмады!", rule: "Ереже",
    topicsWorked: "Өтілген тақырыптар", nextSteps: "Келесі қадамдар", reportNone: "Әңгіме талдау үшін тым қысқа болды.",
    again: "Тағы бір сабақ",
    errAuth: "Сабақты бастау үшін аккаунтқа кір.", errMic: "Микрофонға рұқсат керек — браузерде рұқсат беріп, қайта көр.",
    errNoMinutes: "Бүгінгі минуттар бітті. Базалық квота түн ортасында жаңарады — немесе минут пакетін ал.", buyMinutes: "Минут алу",
    errUnavailable: "Дауысты сабақ уақытша қолжетімсіз. Кейінірек көр.", errGeneric: "Қосылу сәтсіз. Қайта көр.",
    errBusy: (n: number) => `Ұстаз қазір бос емес — сабақтағы орындар толы. ~${n} мин ішінде босайды; автоматты тексереміз.`, busyFree: "Ұстаз босады — бастауға болады!",
    hint: "Еркін сөйле — қателесу қалыпты, ұстаз түзетеді.",
  },
};

function fmt(sec: number) {
  return `${Math.floor(sec / 60)}:${String(sec % 60).padStart(2, "0")}`;
}

/** Audio wave: bars follow the agent's voice when speaking, mic when listening. */
function Wave({ getData, active, color }: { getData: () => Uint8Array; active: boolean; color: string }) {
  const ref = useRef<HTMLCanvasElement>(null);
  useEffect(() => {
    const canvas = ref.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    let raf = 0;
    const BARS = 28;
    const draw = () => {
      const { width, height } = canvas;
      ctx.clearRect(0, 0, width, height);
      let data: Uint8Array | null = null;
      try {
        data = getData();
      } catch {
        /* audio graph not ready */
      }
      const step = data && data.length > 0 ? Math.floor(data.length / BARS) : 0;
      const bw = width / BARS;
      for (let i = 0; i < BARS; i++) {
        const v = active && data && step > 0 ? (data[i * step] ?? 0) / 255 : 0;
        const h = Math.max(height * 0.06, v * height * 0.9);
        const x = i * bw + bw * 0.25;
        const y = (height - h) / 2;
        ctx.fillStyle = color;
        ctx.globalAlpha = active ? 0.9 : 0.35;
        ctx.beginPath();
        ctx.roundRect(x, y, bw * 0.5, h, bw * 0.25);
        ctx.fill();
      }
      raf = requestAnimationFrame(draw);
    };
    raf = requestAnimationFrame(draw);
    return () => cancelAnimationFrame(raf);
  }, [getData, active, color]);
  return <canvas ref={ref} width={560} height={72} className="h-[52px] w-full max-w-[420px]" />;
}

function LiveLesson() {
  const { locale } = useI18n();
  const c = pick(locale, T);

  const [mode, setMode] = useState<Mode>("bolum1");
  const [voice, setVoice] = useState("ahu");
  const [phase, setPhase] = useState<Phase>("idle");
  // plan-engine deep link (?mode=bolum2&focus=izafet,conditionals) — the daily
  // "voice lesson" task pins the mode and the week's focus topics
  const focusOverrideRef = useRef<string[] | null>(null);
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const m = params.get("mode");
    if (m && (MODES as string[]).includes(m)) setMode(m as Mode);
    const focus = (params.get("focus") ?? "").split(",").map((s) => s.trim()).filter(Boolean);
    if (focus.length) focusOverrideRef.current = focus.slice(0, 3); // server re-validates against the registry
  }, []);
  const [err, setErr] = useState<"errAuth" | "errMic" | "errNoMinutes" | "errUnavailable" | "errGeneric" | "errBusy" | null>(null);
  const [busyEta, setBusyEta] = useState(2);
  const [busyFreed, setBusyFreed] = useState(false);
  const [packModal, setPackModal] = useState(false);

  // «занято» → поллим доступность каждые 25 с; освободилось → зелёное «можно начинать»
  useEffect(() => {
    if (err !== "errBusy") return;
    const id = setInterval(async () => {
      try {
        const d = await fetch("/api/voice/session").then((r) => r.json());
        if (d && d.busy === false) {
          setErr(null);
          setBusyFreed(true);
        } else if (d?.etaMinutes) {
          setBusyEta(d.etaMinutes);
        }
      } catch {
        /* сеть мигнула — следующий тик */
      }
    }, 25_000);
    return () => clearInterval(id);
  }, [err]);
  const [lines, setLines] = useState<Line[]>([]);
  const [elapsed, setElapsed] = useState(0);
  const [allowance, setAllowance] = useState<{ baseLeft: number; creditsLeft: number } | null>(null);
  const [lessonFocus, setLessonFocus] = useState<{ id: string; label: Record<Locale, string> }[]>([]);
  // «почему эта тема» — решение ядра агента на языке интерфейса (null = фокус не от ядра)
  const [focusReason, setFocusReason] = useState<string | null>(null);
  const [settle, setSettle] = useState<{ minutes: number | null; seconds: number; fromBase: number; fromCredits: number; report: VoiceReport | null } | null>(null);
  const [reportPending, setReportPending] = useState(false);
  const [settleFailed, setSettleFailed] = useState(false);
  // billing cutoff confirmed server-side: everything after the press is free
  const [wrapFree, setWrapFree] = useState(false);

  const maxSecondsRef = useRef(900);
  // render-safe mirror of maxSecondsRef (lint: no ref reads during render)
  const [maxSeconds, setMaxSeconds] = useState(900);
  const convIdRef = useRef<string | null>(null);
  const settlingRef = useRef(false);
  const wrapRef = useRef<{ requested: boolean; spoke: boolean; timer: ReturnType<typeof setTimeout> | null }>({ requested: false, spoke: false, timer: null });
  const scrollRef = useRef<HTMLDivElement>(null);

  const conversation = useConversation({
    onMessage: (event) => {
      const e = event as { type?: string; user_transcription_event?: { user_transcript?: string }; agent_response_event?: { agent_response?: string } };
      if (e.type === "user_transcript" && e.user_transcription_event?.user_transcript) {
        setLines((l) => [...l, { source: "user", text: e.user_transcription_event!.user_transcript! }]);
      } else if (e.type === "agent_response" && e.agent_response_event?.agent_response) {
        setLines((l) => [...l, { source: "ai", text: e.agent_response_event!.agent_response! }]);
      }
    },
    onDisconnect: () => void settleSession(),
    onError: () => {
      if (phase === "starting") {
        setErr("errGeneric");
        setPhase("idle");
      }
    },
  });
  const { status, isSpeaking } = conversation;

  useEffect(() => {
    if (status === "connected") {
      setPhase((p) => (p === "starting" ? "live" : p));
      if (!convIdRef.current) {
        try {
          convIdRef.current = conversation.getId();
          // survives a closed tab: settled (and removed) on the next visit
          window.localStorage.setItem("lingopro:pending-voice", convIdRef.current);
        } catch {
          /* not ready yet */
        }
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [status]);

  // reconcile a session whose tab was closed mid-call: billing is idempotent
  // server-side, so firing this on every mount is safe
  useEffect(() => {
    const pending = window.localStorage.getItem("lingopro:pending-voice");
    if (!pending || pending === convIdRef.current) return;
    void fetch("/api/voice/session/end", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ conversationId: pending }),
    }).then((r) => {
      if (r.ok || r.status === 404 || r.status === 403) window.localStorage.removeItem("lingopro:pending-voice");
    });
  }, []);

  // oral wrap-up: end once the teacher has delivered the summary and gone
  // quiet. Keyed on BOTH phase and isSpeaking — the old version only reacted
  // to isSpeaking *changes*, so a press made while the teacher was mid-turn
  // never armed the detector and the session hung until the hard timeout,
  // billing all the while (the founder's money-leak bug).
  useEffect(() => {
    if (phase !== "wrapping") return;
    const w = wrapRef.current;
    if (isSpeaking) {
      w.spoke = true;
      return;
    }
    if (w.spoke) {
      // quiet after speaking — 3.5s covers the LLM+TTS gap between her
      // interrupted turn and the actual wrap-up turn
      const t = setTimeout(() => conversation.endSession(), 3500);
      return () => clearTimeout(t);
    }
    // she never started the wrap-up — don't keep the student waiting
    const t = setTimeout(() => conversation.endSession(), 15_000);
    return () => clearTimeout(t);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isSpeaking, phase]);

  useEffect(() => {
    if (phase !== "live" && phase !== "wrapping") return;
    const t = setInterval(() => {
      setElapsed((s) => {
        if (s + 1 >= maxSecondsRef.current) conversation.endSession();
        return s + 1;
      });
    }, 1000);
    return () => clearInterval(t);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [phase]);

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" });
  }, [lines]);

  async function settleSession() {
    const w = wrapRef.current;
    if (w.timer) clearTimeout(w.timer);
    if (settlingRef.current || !convIdRef.current) return;
    settlingRef.current = true;
    setPhase("ended");
    setReportPending(true);
    setSettleFailed(false);
    try {
      // the server polls ElevenLabs too, but a slow finalize can still 404 —
      // retry here so the student is never left review-less without a word
      for (let attempt = 0; attempt < 3; attempt++) {
        let res: Response | null = null;
        try {
          res = await fetch("/api/voice/session/end", {
            method: "POST",
            headers: { "content-type": "application/json" },
            body: JSON.stringify({ conversationId: convIdRef.current }),
          });
        } catch {
          /* network hiccup — falls through to the retry delay */
        }
        if (res?.ok) {
          window.localStorage.removeItem("lingopro:pending-voice");
          const d = await res.json();
          setSettle(d);
          if ((d.minutes ?? 0) > 0) {
            void awardXp("speaking_test", XP.SPEAKING_TEST, {
              dedupKey: `voice:${convIdRef.current}`,
              metadata: { conversationId: convIdRef.current, seconds: d.seconds, mode },
            });
            // credit today's voice_lesson task when the student returns to the plan
            try {
              const now = new Date();
              window.localStorage.setItem(
                "lingopro:voice-done",
                `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`,
              );
            } catch { /* ignore */ }
          }
          // diagnostic v2 §4: the first reviewed lesson supplies the pending
          // Konuşma /25 of the quiz result (idempotent, no-op once attached)
          if (d.report?.valid) void attachKonusmaScore();
          return; // settled — keep settlingRef so duplicate disconnects no-op
        }
        if (attempt < 2) await new Promise((r) => setTimeout(r, 4000 * (attempt + 1)));
      }
      // honest failure with a way forward — settling is idempotent server-side
      setSettleFailed(true);
      settlingRef.current = false;
    } catch {
      setSettleFailed(true);
      settlingRef.current = false;
    } finally {
      setReportPending(false);
    }
  }

  /** Server-side billing cutoff: not a second past this press is charged. */
  function stampCutoff() {
    const id = convIdRef.current;
    if (!id) return;
    void fetch("/api/voice/session/wrap", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ conversationId: id }),
    })
      .then((r) => {
        if (r.ok) setWrapFree(true);
      })
      .catch(() => {
        /* no stamp → full billing, as before */
      });
  }

  /** Instant end: cut billing and tear the session down immediately. */
  function endNow() {
    stampCutoff();
    conversation.endSession();
  }

  function requestWrapUp() {
    const w = wrapRef.current;
    if (w.requested) return;
    w.requested = true;
    w.spoke = false;
    setPhase("wrapping");
    stampCutoff(); // billing stops NOW — the oral wrap-up is on the house
    try {
      // a user message (unlike a contextual update) always triggers a reply
      // turn, so the teacher actually delivers the closing ritual
      conversation.sendUserMessage(WRAP_NOTE);
    } catch {
      conversation.endSession();
      return;
    }
    // if the teacher never wraps up, force-end
    w.timer = setTimeout(() => conversation.endSession(), 45_000);
  }

  async function start() {
    setErr(null);
    setLines([]);
    setSettle(null);
    setElapsed(0);
    setWrapFree(false);
    convIdRef.current = null;
    settlingRef.current = false;
    wrapRef.current = { requested: false, spoke: false, timer: null };
    setPhase("starting");

    try {
      await navigator.mediaDevices.getUserMedia({ audio: true });
    } catch {
      setErr("errMic");
      setPhase("idle");
      return;
    }

    let data: {
      conversationToken: string;
      voiceId: string;
      maxSeconds: number;
      allowance: { baseLeft: number; creditsLeft: number };
      lessonFocus: { id: string; label: Record<Locale, string> }[];
      lessonFocusReason?: string | null;
      dynamicVariables: Record<string, string>;
    };
    try {
      const res = await fetch("/api/voice/session", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ mode, feedbackLang: locale, voiceId: voice, focusTopics: focusOverrideRef.current ?? undefined }),
      });
      if (!res.ok) {
        const d = await res.json().catch(() => ({}));
        if (res.status === 401) setErr("errAuth");
        else if (d.error === "no_minutes") {
          setErr("errNoMinutes");
          setAllowance({ baseLeft: d.baseLeft ?? 0, creditsLeft: d.creditsLeft ?? 0 });
        } else if (d.error === "busy") {
          setErr("errBusy");
          setBusyEta(d.etaMinutes ?? 2);
          setBusyFreed(false);
        } else setErr("errUnavailable");
        setPhase("idle");
        return;
      }
      data = await res.json();
    } catch {
      setErr("errGeneric");
      setPhase("idle");
      return;
    }

    setAllowance(data.allowance);
    setLessonFocus(data.lessonFocus ?? []);
    setFocusReason(data.lessonFocusReason ?? null);
    maxSecondsRef.current = data.maxSeconds;
    setMaxSeconds(data.maxSeconds);
    conversation.startSession({
      conversationToken: data.conversationToken,
      connectionType: "webrtc",
      dynamicVariables: data.dynamicVariables,
      overrides: { tts: { voiceId: data.voiceId } },
    });
  }

  const inCall = phase === "live" || phase === "wrapping";
  const remaining = Math.max(0, maxSeconds - elapsed);
  const report = settle?.report && settle.report.valid ? settle.report : null;

  return (
    <div>
      <h2 className="text-xl font-bold tracking-tight">{c.title}</h2>
      <p className="mt-1 max-w-xl text-sm text-[var(--color-muted)]">{c.subtitle}</p>

      {allowance && (
        <div className="mt-3 flex items-center gap-2 text-xs text-[var(--color-muted)]">
          <span>
            {c.minutes}: <span className="font-semibold text-[var(--color-brand)]">{allowance.baseLeft}</span>
            {allowance.creditsLeft > 0 && <> + {allowance.creditsLeft} {c.purchased}</>}
          </span>
          <button
            type="button"
            onClick={() => setPackModal(true)}
            className="rounded-full border border-[var(--color-brand)]/30 px-2.5 py-0.5 text-[11px] font-semibold text-[var(--color-brand)] transition-colors hover:bg-[var(--color-brand)]/[0.06]"
          >
            + {c.buyMinutes}
          </button>
        </div>
      )}
      {packModal && <VoicePackModal onClose={() => setPackModal(false)} />}

      {phase === "idle" && (
        <div className="glass mt-5 rounded-3xl p-6">
          <div className="flex flex-wrap gap-2">
            {MODES.map((m) => (
              <button key={m} type="button" onClick={() => setMode(m)}
                className={`rounded-full px-4 py-2 text-sm font-medium transition-colors ${mode === m ? "bg-[var(--color-brand)] text-white" : "bg-black/[0.05] text-[var(--color-muted)] hover:bg-black/[0.08]"}`}>
                {c.modes[m]}
              </button>
            ))}
          </div>

          <div className="mt-4 text-xs font-medium text-[var(--color-muted)]">{c.voice}</div>
          <div className="mt-2 flex flex-wrap gap-2">
            {VOICE_OPTIONS.map((v) => (
              <button key={v.id} type="button" onClick={() => setVoice(v.id)}
                className={`rounded-2xl px-4 py-2.5 text-left transition-all ${voice === v.id ? "bg-[var(--color-brand)]/10 ring-1 ring-[var(--color-brand)]/40" : "bg-black/[0.04] hover:bg-black/[0.07]"}`}>
                <span className="block text-sm font-semibold text-[var(--color-foreground)]">{v.name}</span>
                <span className="block text-[11px] text-[var(--color-muted)]">{v.tone[locale]}</span>
              </button>
            ))}
          </div>

          {/* prep: what happens after the button (P0-4 — no surprise mic prompt) */}
          <div className="mt-5 rounded-2xl bg-[var(--color-brand)]/[0.05] p-4">
            <div className="text-sm font-semibold text-[var(--color-foreground)]">
              {pick(locale, { ru: "Как проходит урок", en: "How the lesson works", tr: "Ders nasıl geçer", kk: "Сабақ қалай өтеді" })}
            </div>
            <ul className="mt-2 flex flex-col gap-1.5 text-xs leading-relaxed text-[var(--color-muted)]">
              <li>
                {pick(locale, {
                  ru: "Ahu говорит по-турецки и ведёт урок под твой уровень. Отвечай голосом — ошибаться можно и нужно.",
                  en: "Ahu speaks Turkish and teaches to your level. Answer out loud — mistakes are part of the lesson.",
                  tr: "Ahu Türkçe konuşur ve seviyene göre ders işler. Sesli cevap ver — hata yapmak dersin parçası.",
                  kk: "Ahu түрікше сөйлеп, деңгейіңе сай сабақ жүргізеді. Дауыстап жауап бер — қателесуге болады.",
                })}
              </li>
              <li>
                {pick(locale, {
                  ru: "После нажатия кнопки браузер попросит доступ к микрофону — разреши его.",
                  en: "After you press the button, the browser will ask for microphone access — allow it.",
                  tr: "Düğmeye bastıktan sonra tarayıcı mikrofon izni isteyecek — izin ver.",
                  kk: "Түймені басқаннан кейін браузер микрофонға рұқсат сұрайды — рұқсат бер.",
                })}
              </li>
              <li>
                {pick(locale, {
                  ru: "Урок ~10 минут. В конце Ahu подведёт итог голосом, а письменный разбор появится на экране.",
                  en: "The lesson is ~10 minutes. Ahu wraps up out loud, and a written review appears on screen.",
                  tr: "Ders ~10 dakika. Sonunda Ahu sözlü özet yapar, yazılı değerlendirme ekranda görünür.",
                  kk: "Сабақ ~10 минут. Соңында Ahu ауызша қорытады, жазбаша талдау экранда шығады.",
                })}
              </li>
            </ul>
          </div>

          {err && (
            <div className="mt-4 rounded-xl bg-[#d97706]/10 px-4 py-3 text-sm text-[#92400e]">
              {/* «занято» — не ошибка: честный статус с ETA и автопроверкой */}
              <p>{err === "errBusy" ? c.errBusy(busyEta) : c[err]}</p>
              {/* every error offers a way forward (P0-5) */}
              <div className="mt-2 flex flex-wrap gap-2">
                {err === "errAuth" ? (
                  <a href="/login" className="rounded-full bg-[#92400e] px-4 py-1.5 text-xs font-semibold text-white">
                    {pick(locale, { ru: "Войти", en: "Sign in", tr: "Giriş yap", kk: "Кіру" })}
                  </a>
                ) : err === "errNoMinutes" ? (
                  <>
                    <button type="button" onClick={() => setPackModal(true)} className="rounded-full bg-[#92400e] px-4 py-1.5 text-xs font-semibold text-white">
                      🎙️ {c.buyMinutes}
                    </button>
                    <a href="/dashboard" className="rounded-full border border-[#92400e]/40 px-4 py-1.5 text-xs font-semibold text-[#92400e]">
                      {pick(locale, { ru: "К плану дня", en: "To today's plan", tr: "Günün planına", kk: "Күн жоспарына" })}
                    </a>
                  </>
                ) : err === "errBusy" ? null : (
                  <button type="button" onClick={start} className="rounded-full bg-[#92400e] px-4 py-1.5 text-xs font-semibold text-white">
                    {pick(locale, { ru: "Попробовать снова", en: "Try again", tr: "Tekrar dene", kk: "Қайта көру" })}
                  </button>
                )}
              </div>
            </div>
          )}
          {busyFreed && !err && (
            <div className="mt-4 rounded-xl bg-[#16a34a]/10 px-4 py-3 text-sm font-medium text-[#166534]">
              ✅ {c.busyFree}
            </div>
          )}

          <div className="mt-5 flex flex-wrap items-center gap-3">
            <button type="button" onClick={start} className="btn-primary rounded-full px-6 py-3 text-sm font-semibold">
              🎙️ {c.start}
            </button>
            <button
              type="button"
              onClick={() => setPackModal(true)}
              className="btn-ghost rounded-full px-5 py-3 text-sm font-medium"
            >
              + {c.buyMinutes}
            </button>
          </div>
          <p className="mt-3 text-xs text-[var(--color-muted)]">{c.hint}</p>
          <a href="/dashboard/speaking/push" className="mt-2 inline-block text-xs text-[var(--color-muted)] underline-offset-2 hover:underline">
            {pick(locale, { ru: { t: "Текстовый режим (push-to-talk)" }, en: { t: "Text mode (push-to-talk)" }, tr: { t: "Metin modu (push-to-talk)" }, kk: { t: "Мәтін режимі (push-to-talk)" } }).t}
          </a>
        </div>
      )}

      {(phase === "starting" || inCall) && (
        <div className="glass mt-5 rounded-3xl p-6">
          {lessonFocus.length > 0 && (
            <div className="mb-3">
              <div className="flex flex-wrap items-center gap-1.5">
                <span className="text-[11px] font-semibold uppercase tracking-wide text-[var(--color-muted)]">{c.focus}:</span>
                {lessonFocus.map((f) => (
                  <span key={f.id} className="rounded-full bg-[var(--color-brand)]/[0.08] px-2.5 py-0.5 text-[11px] font-medium text-[var(--color-brand)]">
                    {f.label[locale]}
                  </span>
                ))}
              </div>
              {focusReason && (
                <p className="mt-1.5 text-[11px] leading-snug text-[var(--color-muted)]">💡 {focusReason}</p>
              )}
            </div>
          )}

          <div className="flex items-center justify-between">
            <span className="text-sm font-medium text-[var(--color-foreground)]">
              {phase === "starting" ? c.starting : phase === "wrapping" ? c.wrapping : isSpeaking ? c.speaking : c.listening}
            </span>
            {inCall && (
              <span className={`text-sm font-semibold tabular-nums ${remaining <= 60 ? "text-[#dc2626]" : "text-[var(--color-muted)]"}`}>
                {fmt(elapsed)} / {fmt(maxSeconds)}
              </span>
            )}
          </div>

          {phase === "wrapping" && wrapFree && (
            <div className="mt-2 inline-flex items-center gap-1.5 rounded-full bg-[#16a34a]/10 px-3 py-1 text-xs font-medium text-[#15803d]">
              ✓ {c.wrapFreeNote}
            </div>
          )}

          <div className="mt-3 flex justify-center rounded-2xl bg-black/[0.03] px-4 py-2">
            <Wave
              active={inCall}
              color={isSpeaking ? "#6366f1" : "#16a34a"}
              getData={isSpeaking ? conversation.getOutputByteFrequencyData : conversation.getInputByteFrequencyData}
            />
          </div>

          <div ref={scrollRef} className="mt-4 flex max-h-64 flex-col gap-2 overflow-y-auto rounded-2xl bg-black/[0.03] p-4">
            {lines.length === 0 && <span className="text-xs text-[var(--color-muted)]">…</span>}
            {lines.map((l, i) => (
              <div key={i} className={`max-w-[85%] rounded-2xl px-3.5 py-2 text-sm leading-relaxed ${l.source === "user" ? "self-end bg-[var(--color-brand)]/10 text-[var(--color-foreground)]" : "self-start bg-white shadow-sm text-[var(--color-foreground)]"}`}>
                {l.text}
              </div>
            ))}
          </div>

          {phase === "live" && (
            <p className="mt-4 rounded-xl bg-black/[0.03] px-3.5 py-2.5 text-xs leading-relaxed text-[var(--color-muted)]">
              💬 {c.endHint}
            </p>
          )}
          {phase === "live" && (
            <div className="mt-3 flex items-center gap-4">
              <button type="button" onClick={requestWrapUp} className="btn-primary rounded-full px-5 py-2.5 text-sm font-medium">
                🏁 {c.end}
              </button>
              <button type="button" onClick={endNow} className="text-xs text-[var(--color-muted)] underline-offset-2 hover:underline">
                {c.endNow}
              </button>
            </div>
          )}
          {phase === "wrapping" && (
            <div className="mt-4">
              {/* the student is never locked in: skip the (free) wrap-up any time */}
              <button type="button" onClick={() => conversation.endSession()} className="text-xs text-[var(--color-muted)] underline-offset-2 hover:underline">
                {c.endNow}
              </button>
            </div>
          )}
        </div>
      )}

      {phase === "ended" && (
        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="glass mt-5 rounded-3xl p-6">
          <h3 className="text-base font-semibold text-[var(--color-foreground)]">{c.ended}</h3>
          {settle &&
            settle.minutes != null &&
            (settle.minutes > 0 ? (
              <p className="mt-1 text-sm text-[var(--color-foreground)]">
                {c.spent}: <b>{settle.minutes} {c.min}</b> ({settle.fromBase} {c.fromBase}
                {settle.fromCredits > 0 && <>, {settle.fromCredits} {c.fromCredits}</>}) · {fmt(settle.seconds)}
              </p>
            ) : (
              <p className="mt-1 text-sm text-[var(--color-muted)]">{c.short}</p>
            ))}

          {reportPending && (
            <div className="mt-4 flex items-center gap-3 rounded-xl bg-[var(--color-brand)]/[0.06] px-4 py-3 text-sm text-[var(--color-foreground)]">
              <span className="h-4 w-4 animate-spin rounded-full border-2 border-[var(--color-brand)] border-t-transparent" />
              {c.reportPreparing}
            </div>
          )}

          {settleFailed && (
            <div className="mt-4 rounded-xl bg-[#d97706]/10 px-4 py-3 text-sm text-[#92400e]">
              <p>{c.settleFailed}</p>
              <button
                type="button"
                onClick={() => void settleSession()}
                className="mt-2 rounded-full bg-[#92400e] px-4 py-1.5 text-xs font-semibold text-white"
              >
                {c.settleRetry}
              </button>
            </div>
          )}

          {!reportPending && !settleFailed && settle && !report && (settle.minutes == null || settle.minutes > 0) && (
            <p className="mt-3 text-sm text-[var(--color-muted)]">{c.reportNone}</p>
          )}

          {report && (
            <div className="mt-4 flex flex-col gap-4">
              <div className="text-sm font-semibold text-[var(--color-foreground)]">{c.reportTitle}</div>
              {report.summary && <p className="text-sm leading-relaxed text-[var(--color-foreground)]">{report.summary}</p>}

              <div className="grid gap-2 sm:grid-cols-2">
                {(["fluency", "grammar", "vocab", "coherence"] as const).map((k) => (
                  <div key={k} className="rounded-xl bg-black/[0.03] p-3">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-semibold text-[var(--color-foreground)]">{c.crit[k]}</span>
                      <span className="text-sm font-bold text-[var(--color-brand)]">{report.criteria[k].score}/5</span>
                    </div>
                    {report.criteria[k].comment && <p className="mt-1 text-xs text-[var(--color-muted)]">{report.criteria[k].comment}</p>}
                  </div>
                ))}
              </div>

              <div>
                <div className="text-xs font-semibold uppercase tracking-wide text-[#d97706]">{c.errors}</div>
                {report.errors.length === 0 ? (
                  <p className="mt-2 text-sm text-[#16a34a]">{c.noErrors}</p>
                ) : (
                  <ul className="mt-2 flex flex-col gap-2.5">
                    {report.errors.map((e, i) => (
                      <li key={i} className="rounded-xl bg-black/[0.03] p-3.5 text-sm">
                        <div className="flex flex-wrap items-center gap-2">
                          <span className="rounded bg-[#dc2626]/10 px-2 py-0.5 font-medium text-[#b91c1c] line-through decoration-[#dc2626]/50">{e.quote}</span>
                          <span aria-hidden>→</span>
                          <span className="rounded bg-[#16a34a]/10 px-2 py-0.5 font-medium text-[#15803d]">{e.correction}</span>
                        </div>
                        <div className="mt-1.5 text-[var(--color-foreground)]"><b>{c.rule}:</b> {e.rule}</div>
                        <div className="mt-0.5 text-[var(--color-muted)]">{e.explanation}</div>
                      </li>
                    ))}
                  </ul>
                )}
              </div>

              {report.topics_worked.length > 0 && (
                <div>
                  <div className="text-xs font-semibold uppercase tracking-wide text-[var(--color-muted)]">{c.topicsWorked}</div>
                  <div className="mt-2 flex flex-wrap gap-1.5">
                    {report.topics_worked.map((id) => {
                      const t = topicById(id);
                      return t ? (
                        <span key={id} className="rounded-full bg-[var(--color-brand)]/[0.08] px-2.5 py-1 text-xs font-medium text-[var(--color-brand)]">
                          {t.label[locale]}
                        </span>
                      ) : null;
                    })}
                  </div>
                </div>
              )}

              {report.next_steps.length > 0 && (
                <div className="rounded-xl bg-[var(--color-brand)]/[0.05] p-4">
                  <div className="text-xs font-semibold uppercase tracking-wide text-[var(--color-brand)]">{c.nextSteps}</div>
                  <ul className="mt-2 flex flex-col gap-1 text-sm text-[var(--color-foreground)]">
                    {report.next_steps.map((s, i) => (
                      <li key={i}>• {s}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          )}

          {lines.length > 0 && (
            <details className="mt-4">
              <summary className="cursor-pointer text-xs font-semibold uppercase tracking-wide text-[var(--color-muted)]">{c.transcript}</summary>
              <div className="mt-2 flex max-h-56 flex-col gap-2 overflow-y-auto rounded-2xl bg-black/[0.03] p-4">
                {lines.map((l, i) => (
                  <div key={i} className={`max-w-[85%] rounded-2xl px-3.5 py-2 text-sm ${l.source === "user" ? "self-end bg-[var(--color-brand)]/10" : "self-start bg-white shadow-sm"}`}>{l.text}</div>
                ))}
              </div>
            </details>
          )}

          <button type="button" onClick={() => setPhase("idle")} className="btn-primary mt-5 rounded-full px-5 py-2.5 text-sm">
            {c.again}
          </button>
        </motion.div>
      )}
    </div>
  );
}

export default function LiveLessonPage() {
  return (
    <ConversationProvider>
      <LiveLesson />
    </ConversationProvider>
  );
}
